server:
  port: 1010

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        service-name: gateway

    gateway:
      routes:
        - id: data-service1  #请求 http://localhost:8100/data-service1/test会转发到data-producer服务，
          uri: lb://order  #在服务注册中心找服务名为 data-producer的服务，
          predicates:
            - Path=/data-service1/**
          filters:
            - StripPrefix=1
        - id: data-service2  #请求 http://localhost:8100/data-service1/test会转发到data-producer服务，
          uri: lb://waiter  #在服务注册中心找服务名为 data-producer的服务，
          predicates:
            - Path=/data-service2/**
          filters:
            - StripPrefix=1